package ru.kpfu.itis.auth.api.presentation

enum class AuthErrorType {
    INVALID_USERNAME,
    INVALID_PHONE,
    INVALID_CODE,

    PHONE_ALREADY_REGISTERED,
    PHONE_NOT_REGISTERED,
    REGISTRATION_FAILED,

    WRONG_CODE,
    TOO_MANY_ATTEMPTS,
    WAIT_BEFORE_RESEND,

    NETWORK_ERROR,
    FIREBASE_AUTH_ERROR,
    FIRESTORE_ERROR,

    USER_NOT_AUTHENTICATED,
    LOGOUT_FAILED,
    UNKNOWN_ERROR;
}
